name: Cypress test agoda
on: [push]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with: 
                build: npx Cypress run --spec C:\Users\lijom\Cypress\searchhotel\cypress\integration\examples\searchhotel.js --headed --browser chrome
                start: npm start
