name: Cypress test agoda
on: [push]
jobs:
    cypress-run:
        runs-on: windows
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Cypress run
              uses: cypress-io/github-action@v5
              